#!/bin/bash

set -eufo pipefail

source scripts/01-setup

scripts/02-installation

# allow sudo without password for installation
sed -i '/^# %wheel ALL=(ALL:ALL) NOPASSWD: ALL$/s/^# //' /mnt/etc/sudoers

SCRIPTS='/scripts'
mkdir /mnt$SCRIPTS
mount -o bind,ro scripts /mnt$SCRIPTS
UTILS='/utils'
mkdir /mnt$UTILS
mount -o bind,ro utils /mnt$UTILS

arch-chroot /mnt $SCRIPTS/03-configure-system

unset PASSWORD
unset PASSWORD_CONFIRM
export -p > utils/variables
systemd-nspawn -u "$USERNAME" -D /mnt $SCRIPTS/04-user-setup

umount /mnt$SCRIPTS
rmdir /mnt$SCRIPTS
umount /mnt$UTILS
rmdir /mnt$UTILS

# reset sudo privileges
sed -i '/^# %wheel ALL=(ALL:ALL) ALL$/s/^# //' /mnt/etc/sudoers
sed -i '/^%wheel ALL=(ALL:ALL) NOPASSWD: ALL$/s/^/# /' /mnt/etc/sudoers

printf '\nInstallation successful!\n\n'

