#!/bin/bash

grep -q 'HOME' <<< "$CONNECTION_ID" && home='true' || home='false'
grep -q 'syncthing' <<< "$(ufw status)" && enabled='true' || enabled='false'

if [[ $home = 'true' ]] && [[ $enabled = 'false' ]]; then
    ufw allow syncthing
    ufw reload
elif [[ $home = 'false' ]] && [[ $enabled = 'true' ]]; then
    ufw delete allow syncthing
    ufw reload
fi

