#!/bin/bash

set -eufo pipefail

# Set the console keyboard layout
localectl set-keymap uk

# Verify the boot mode
if ! [ -f /sys/firmware/efi/fw_platform_size ]; then
    echo 'System is not booted in UEFI mode'
    exit 1
fi
if [[ $(cat /sys/firmware/efi/fw_platform_size) -ne 64 ]]; then
    echo 'System is booted into 32-bit UEFI mode'
    exit 1
fi

# Partition the disks
if [[ $AUTO_PARTITION = 'yes' ]]; then
    sgdisk -Z "${DRIVE}"
    sgdisk -o "${DRIVE}"
    sgdisk -I -n 1:0:+1000M -t=1:ef00 "${DRIVE}"
    sgdisk -I -n 2:0:0      -t=2:8300 "${DRIVE}"
fi

# Format the partitions
mkfs.fat -F 32 "$EFI_PARTITION"
mkfs.ext4 "$ROOT_PARTITION"

# Mount the file systems
mount "$ROOT_PARTITION" /mnt
mount --mkdir "$EFI_PARTITION" /mnt"$ESP"

# Select the mirrors
mv /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.backup
xargs reflector < utils/reflector.conf

# Manually initialise pacman keyring if required
if grep -q 'Active: failed' <<< "$(systemctl status pacman-init.service)"; then
    pacman-key --init
fi

# Install essential packages
sed -i 's/^#ParallelDownloads/ParallelDownloads/' /etc/pacman.conf
sed -i '/^#\[multilib\]$/{s/^#//;n;s/^#//}' /etc/pacman.conf
pacstrap -K /mnt base base-devel linux linux-firmware

# Fstab
genfstab -U /mnt >> /mnt/etc/fstab

