#!/bin/bash

set -eufo pipefail

USER=$USERNAME
HOME=/home/$USERNAME
cd "$HOME"

# Enable pipewire-pulse.service
sudo systemctl --user enable pipewire-pulse.service

# Bare clone dotfiles repo and set up config alias
git clone --bare https://github.com/ZakDggn/dotfiles "$HOME"/.dotfiles
config="git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME"
$config config status.showUntrackedFiles no
mv .bashrc .bashrc.backup
$config checkout

# Install dwm
git clone https://github.com/ZakDggn/dwm "$HOME"/dwm
git clone https://github.com/ZakDggn/dwmblocks-async "$HOME"/dwmblocks-async
cd "$HOME"/dwm
sudo make install
cd "$HOME"/dwmblocks-async
sudo make install
cd "$HOME"
sudo mkdir -p /usr/share/xsessions
sudo cp "$UTILS"/dwm.desktop /usr/share/xsessions/dwm.desktop

# Create user's home directories
for d in Desktop Documents Downloads Music Pictures Public Templates Videos; do
  if [[ -d "$HDD_MNT"/$d ]]; then
    ln -s "$HDD_MNT"/$d "$HOME"/$d
  else
    mkdir "$HOME"/$d
  fi
done

# Copy wallpaper to Pictures
cp "$UTILS"/wallpaper.png "$HOME"/Pictures/

