#!/bin/bash

set -eufo pipefail

source /utils/variables

USER=$USERNAME
HOME=/home/$USERNAME
cd "$HOME"

# Change default shell to fish
sudo chsh -s /usr/bin/fish "$USERNAME"

# Install Informant
yay -S --noconfirm informant
sudo informant read --all
sudo usermod -aG informant "$USERNAME"

# Enable pipewire-pulse service
systemctl --user enable pipewire-pulse.service

# Enable syncthing service
systemctl --user enable syncthing.service

# Install tmux plugin manager
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# Bare clone dotfiles repo and set up config alias
git clone --bare https://github.com/ZakDggn/dotfiles "$HOME"/.dotfiles
config="git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME"
$config config status.showUntrackedFiles no
rm .bashrc
rm .bash_profile
$config checkout
$config submodule update --init
$config remote set-url origin git@github.com:ZakDggn/dotfiles
sed -i '/\[remote/a \	fetch = +refs\/heads\/\*:refs\/remotes\/origin\/\*' "$HOME"/.dotfiles/config

# Create user's home directories
for d in Documents Downloads Music Pictures Videos; do
    if [[ -d "$HDD_MNT"/$d ]]; then
        ln -s "$HDD_MNT"/$d "$HOME"/$d
    else
        mkdir "$HOME"/$d
    fi
done

# Create screenshots directory for grimshot
mkdir -p "$HOME"/Pictures/Screenshots
