#!/bin/bash

set -e

function user_confirmation {
  local CONFIRMED
  read -rp "$1 [Y/n]: " CONFIRMED
  if ! [[ $CONFIRMED =~ ^[Yy]|^\s*$ ]]; then
    exit 1
  fi
}

# AMD
sudo pacman -S --needed libva-mesa-driver libva-utils

echo "Verify output of vainfo:"
vainfo

echo "Verify with mpv --hwdec=vaapi video_filename"
echo "Set media.ffmpeg.vaapi.enabled to true in about:config"
user_confirmation "Verify usage in Firefox?" 
MOZ_LOG="FFmpegVideo:5" firefox 2>&1 | tee firefox.log | grep --color=always -A 1 'VA-API' | less -R


# NVIDIA
# https://github.com/elFarto/nvidia-vaapi-driver
